apps:
  - name: avatars-service-api
    environment: production
    codebase: avatars-service
    replicaCount: 1
    container:
      image:
        repository: osuakatsuki/avatars-service
        tag: latest
      port: 80
      env:
        - name: APP_COMPONENT
          value: api
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
    service:
      type: ClusterIP
      port: 80
