apps:
  - name: avatars-service-api
    environment: production
    codebase: avatars-service
    replicaCount: 1
    container:
      image:
        repository: osuakatsuki/avatars-service
        tag: latest
      port: 80
      readinessProbe:
        httpGet:
          path: /_health
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      resources:
        limits:
          cpu: 400m
          memory: 400Mi
        requests:
          cpu: 250m
          memory: 250Mi
      env:
        - name: APP_COMPONENT
          value: api
      imagePullSecrets:
        - name: osuakatsuki-registry-secret
    service:
      type: ClusterIP
      port: 80
